### ISSUE TITLE
Altering bfile does not allow rematerialization

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/pychapel#11]
I ran a python program which used a bfile, and discovered that the output was not what I expected.  When I altered the bfile so that it would generate different output, the output remained the same.  I had to reinstall pychapel for the updated version of the function to be used.  Needless to say, reinstalling the tool seems like a steep price for utilizing an updated file.

**Comment by lydia-duncan** [comment]
This is likely also the case for sfiles, but I haven't checked yet.

**Comment by thomasvandoren** [comment]
pychapel caches compiled files, IIRC. This sounds like a bug with the cache algorithm.

**Comment by lydia-duncan** [comment]
Yeah, that's what I was thinking.  I would be nice for the cache algorithm to take into account "time since modified" or something along those lines.

**Comment by thomasvandoren** [comment]
It might be easier to checksum the file. If the checksum changes, update cache.

**Comment by lydia-duncan** [comment]
Upon further investigation, this is a result of the sfiles and bfiles in docs/source/examples/[sfiles | bfiles] being copied to a default directory when pyChapel is installed.  Closing the issue.
