### ISSUE TITLE
Support relative paths of sfile

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/pychapel#76]
Does not appear to be documented if it exists.  But to separate source files, a common pattern (in other languages) is

```
src/python/module
src/chpl/module
```

When calling out to `sfiles` PyChapel should support relative paths.  For instance in 

```
src/python/module/caller.py

from pych.extern import Chapel

@Chapel(sfile="../../src/chpl/module/hellolib.exported.chpl")
def hello_caller():
    return None
```

**Comment by lydia-duncan** [comment]
Ah, here we go: https://github.com/chapel-lang/pychapel/blob/master/docs/source/examples/test_unusual_sfile_loc.py

**Comment by lydia-duncan** [comment]
Something about the install path is interesting, meaning that I think the join is necessary.  You're right that it should be documented

**Comment by buddha314** [comment]
Should we re-focus this ticket on documentation, then?

**Comment by lydia-duncan** [comment]
Sure, unless you want it to focus on whether the join should be necessary

**Comment by buddha314** [comment]
Oh, I missed that part of your comment. I think you mean this:

```
currentloc = os.path.dirname(os.path.realpath(__file__))

# Note: depends on test living in a specific location relative to
# mymodule.chpl.  Not ideal, but also not a huge issue.
@Chapel(sfile=os.path.join(currentloc + "/../../../module/ext/src/mymodule.chpl"))
def hello_mymodule():
    return None
```

I don't know if that's a standard pattern or not, honestly.  You probably have a more educated opinion than I do.  If it's standard, then we should probably get it into the documentation.

**Comment by lydia-duncan** [comment]
I suspect it is there because we get a different result if py.test is called at the top level or in docs/source/examples.  Probably fine to leave it, but should definitely recommend using that join.

**Comment by buddha314** [comment]
I was able to use the os.path join method, so it looks like the current stack does handle this.  I'll close the ticket.  See https://github.com/chapel-lang/pychapel/issues/78 for an example.
