### ISSUE TITLE
Cray-internal nightly pychapel correctness test Jenkins build fails unit tests

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/pychapel#95]
2018-03-06
New test failures from this morning's nightly build. 
```
docs/source/examples/test_finance_chapel_numpy.py
docs/source/examples/test_finance_chapel_numpy_flatten.py
collecting docs/source/examples/test_finance_python_numpy.py
collecting docs/source/examples/test_sparse_array_error_msg.py
```
Previous nightly build was successful. 
There were no changes to source or test environment.

**Comment by awallace-cray** [comment]
Console log showing representative error.
```
_____ ERROR collecting docs/source/examples/test_sparse_array_error_msg.py _____
ImportError while importing test module '/ptmp/jenkins/chapel-ci/workspace/correctness-test-pychapel/docs/source/examples/test_sparse_array_error_msg.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
docs/source/examples/test_sparse_array_error_msg.py:6: in <module>
    import matplotlib
../../shiningpanda/jobs/5edffbc6/virtualenvs/d41d8cd9/lib/python2.7/site-packages/matplotlib/__init__.py:127: in <module>
    from . import cbook
../../shiningpanda/jobs/5edffbc6/virtualenvs/d41d8cd9/lib/python2.7/site-packages/matplotlib/cbook/__init__.py:13: in <module>
    import bz2
E   ImportError: No module named bz2
```

**Comment by awallace-cray** [comment]
The change between 2018-03-05 (tests pass) and 2018-03-06 (4 failures) was that `pip install requirements.txt` got matplotlib/2.1.2 one day, matplotlib/2.2.0 the next. 

Unlike matplotlib/2.1.2, matplotlib/2.2.0 wants to `import bz2`. We do not have bz2 in the python env used on this test machine, which is an older SLES-11 system and thus does not even have python 2.7 installed on the system. We therefore use a hand-built python 2.7 version. We could get  Cray I.T. to install package `bzip2-devel`, rebuild our python 2.7, and this test job would likely work. 

Or, we could constrain matplotlib<2.2.0 in the requirements files.

**Comment by awallace-cray** [comment]
2018-03-07 06:30 

I just tried the un-modified test job (ie, matplotlib/2.2.0) on a newer, SLES-12 build slave. 

First tried it with the system-installed Python 2.7.  This failed, because matplotlib also requires Tck/Tk modules, which are not included in the system-installed Python 2.7.  That problem was known- I just forgot about it.  Like matplotlib's bz2-dependency, Tcl/Tk doesn't do anything for pychapel itself- it only satisfies a dependency in something used in the Python unit test harness. 

Tcl/Tk modules are available in the built-from-source Python 2.7 that I installed for these systems when they were upgraded to SLES-12. So, I retried the test job, still using un-modified source w matplotlib/2.2.0. Everything passed. `bzip2-devel` must have been present when I built that Python.

**Comment by awallace-cray** [comment]
So, we could either move the test job to run on a SLES-12 build slave, or apply PR #96, or both. 
At the moment, I like moving the test job better.

**Comment by lydia-duncan** [comment]
The bz2 requirement sounds familiar.  I'm fine with moving the job, but we will have to note the new dependency for users installing locally (as I'm not sure how prevalent bzip2 will be on newer systems)

**Comment by awallace-cray** [comment]
Surveyed internal system-installed `/usr/bin/python` versions, and whether they had bz2 support and/or Tkinter (Tcl/tk) support.  Conclusion: bz2 is very likely to be supported, more so than Tkinter for example (at least on non-desktop machines). 

System | Python 2 version | bz2? | Tkinter? | comment
--------|------------------|------|---------|----------
SLES-12 (I.T.-built) | 2.7.13 | Y | N |
SLES-11 (I.T.-built) | 2.6.9 | Y | N |
centos7 (user-built) | 2.7.5 | Y | N |
ubuntu-64 16.04 (user-built) | 2.7.12 | Y | Y | has Tkinter because I installed `python-tk` package when I built the VM (because pychapel!)
ubuntu-32 16.04 (user-built) | 2.7.12 | Y | N | no Tkinter, because I didn't bother adding `python-tk` for pychapel

**Comment by awallace-cray** [comment]
However, lets put in the matplotlib<2.2.0 requirement (PR #96). I think that is much less trouble than it will take to move this test job. 
The chapcsNN machines are all complicated by that Slurm management policy. When the chapNN are replaced or upgraded to SLES-12, we might remove that matplotlib constraint.

**Comment by lydia-duncan** [comment]
Sounds good, thanks!

**Comment by awallace-cray** [comment]
Tests pass.
